### PR TITLE
Added a readme & chromebook specs to repository

### PR DESCRIPTION
**Pull request by sa1f**

### CODE REVIEW

**Comment by waldyrious** [comment]
+1 for adding a readme (I was going to suggest that) but I don't think duplicating the FAQ is a good idea. One could point the reader to the site to read it there. That way, there's no problem of having them go out of sync.

I do think it's important to have that "Adding devices to the 'Known Screens' list" section, and I'd also suggest to have a small intro on how this works (for instance, why it can't be automatically detected -- with links to resources such as [this quirksmode post](http://www.quirksmode.org/blog/archives/2012/07/more_about_devi.html), which discusses `devicePixelRatio`)

**Comment by LeaVerou** [comment]
Agreed with @waldir about the readme. Also please, as a general rule, don't send a PR with multiple unrelated changes. For example, now I want to merge the device addition, but not the readme, and I can't.

But otherwise, thanks for contributing!

**Comment by waldyrious** [comment]
[This StackOverflow answer](http://stackoverflow.com/a/21767407/266309) also contains a great overview of this topic. More good resources that would be worth linking to:
- [Responsive Typography is a Physical Discipline, But Your Computer Doesn’t Know It (Yet)](http://alistapart.com/column/responsive-typography-is-a-physical-discipline) (A List Apart)
- [Let's Get Physical (Units)](http://smus.com/physical-units/) (Boris Smus)

**Comment by LeaVerou** [comment]
Since the requested changes have not been made, I'm closing this PR.

**Pull request closed without merging**
