### PR TITLE
Added Samsung Galaxy S III

### PR DESCRIPTION
**Pull request by giannoug**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi there,

Thanks!
Why did you change the S4 though? 5 inches was correct http://www.gsmarena.com/samsung_i9500_galaxy_s4-5125.php

**Comment by giannoug** [comment]
Oops, that was a mistake. Sorry for that! Do you want me to make another merge request?

**Comment by LeaVerou** [comment]
You can add commits to this one, though I don’t know how.

**Comment by giannoug** [comment]
Hmm... It (GitHub) added a commit to my commit. I think this is the only possible way to fix it, apart from creating a new merge request (with a new commit). I hope this helps!

**Comment by LeaVerou** [comment]
Thanks!

**Pull request merged**
