### PR TITLE
Always set a background color on the body

### PR DESCRIPTION
**Pull request by nhoizey**
Or it will take the background color set in the browser preferences… ;-)

capture decran 2013-10-07 a 13 20 41

### CODE REVIEW

**Comment by LeaVerou** [comment]
If the user set a background colour in their preferences, shouldn’t it be respected? If anything, what seems to be wrong here is that the table doesn’t match.

**Comment by nhoizey** [comment]
If you respect the background color set by the user, you should also respect the text color, else there will be issues. That's why it seems safer to always set none or both of them.

What do you mean by "the table doesn’t match"?
I'm on a 15" MacBook Pro, but you can't detect physical size, don't you?

**Comment by LeaVerou** [comment]
I meant the table doesn’t match with the background color set. Anyway, I see your point about text color. Once CSS gets color modification functions it would be easy to respect that too. For now, I’m merging this PR. Thanks!

**Comment by nhoizey** [comment]
You're welcome!

**Comment by nhoizey** [comment]
Just for the record, here is the WCAG Criterion: http://www.w3.org/TR/WCAG-TECHS/F24.html

**Comment by LeaVerou** [comment]
Thanks! Yes, that makes total sense.

**Pull request merged**
