### PR TITLE
Update screens.json

### PR DESCRIPTION
**Pull request by tijsdeboeck**
Added Samsung Galaxy Mini 2, Jiayu G4S, and updated some specs of existing devices (ppi & dppx mostly)

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hey, thanks for the contribution!
When ppi can be computed from the results we do not include it. We only include it when it’s off by a bit from what we can compute. Also, we don't include dppx when it's 1, as that is its default anyway.
Could you please adjust your PR to remove those additions? Thanks!

**Comment by tijsdeboeck** [comment]
Hi Lea, Thanks for the feedback, I've changed it and sand in a new PR.

**Comment by LeaVerou** [comment]
You could have just edited this PR, but ok…

**Comment by tijsdeboeck** [comment]
Yes, I saw that afterwards as well :/ This is the second PR I've done so far, and just getting the hang of it. Anyways, thanks for merging the new PR :)

**Pull request closed without merging**
