### PR TITLE
Add Kindle Fire HDX 7 and Kindle Fire HDX 8.9 into screens

### PR DESCRIPTION
**Pull request by rosylilly**
@LeaVerou Please merge it :smiley_cat:

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hey, thanks! Why is the diagonal size in the device name as well?

**Comment by rosylilly** [comment]
Oh, is a diagonal size unnecessary in name field? I'll remove it.

**Comment by LeaVerou** [comment]
Thanks!

**Comment by rosylilly** [comment]
Thank you for merge :smiley_cat:

**Pull request merged**
