### PR TITLE
Add Sony Xperia Z5 Compact

### PR DESCRIPTION
**Pull request by cassidyjames**
Specs from http://www.sonymobile.com/global-en/products/phones/xperia-z5-compact/specifications/

### CODE REVIEW

**Comment by LeaVerou** [comment]
Merge conflicts :(

**Comment by cassidyjames** [comment]
No worries, I'll get that fixed right up.

**Comment by LeaVerou** [comment]
Now it shows all the devices you've added in the previous PRs as changes of this PR, and it still shows merge conflicts :-S

**Comment by cassidyjames** [comment]
Yeah my bad! Resolved locally and updated now.

**Pull request merged**
