### PR TITLE
Add .editorconfig file

### PR DESCRIPTION
**Pull request by omniwired**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks but have you realized these config settings are completely against the coding style of the project? I know they’re defaults, but there’s no way I’m merging something that defines that the indentation style is 4 spaces (yuck)

**Comment by omniwired** [comment]
what would be a good value?

**Comment by LeaVerou** [comment]
A quick look at the codebase would give you the answer much quicker than I ever could.
The project (as well as all my projects) uses [tabs for indentation & spaces for alignment](http://lea.verou.me/2012/01/why-tabs-are-clearly-superior/).

**Comment by omniwired** [comment]
wow sorry I wasn't enlightened

**Comment by LeaVerou** [comment]
Don't worry, it's never too late for enlightement :P

Merged, thanks! Sorry for the delay & happy new year!

**Pull request merged**
