### PR TITLE
Auto calculate ppi from json

### PR DESCRIPTION
**Pull request by alimd**
Easier/faster develope devices list, related to #11

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi there,

Thanks for all this work!! Some minor changes requested inline, mostly to do with coding style.

**Comment by alimd** [comment]
> You are reassigning device.ppi to itself even when it exists, that’s what I was talking about.

ok, i will change it

Could you please tell me which one is better for all `if`.

```
if (!device.ppi) {
  device.ppi = calcDpi(device.w, device.h, device.d);
}
```

or

```
device.ppi || ( device.ppi = calcDpi(device.w, device.h, device.d) );
```

**Comment by alimd** [comment]
359c7ee has error and force replaced by eda221c

**Comment by alimd** [comment]
If you don't like `Improve codding readability` as a separate commit. i can open new pull request again.

**Comment by LeaVerou** [comment]
Merged, thanks!

**Comment by LeaVerou** [comment]
Regarding which version is better, I think both are the same perf-wise. The former is probably easier to read for most people.

**Pull request merged**
