### PR TITLE
Added Sony Xperia Miro and Samsung Galaxy Young

### PR DESCRIPTION
**Pull request by incognitojam**
I was unable to make changes to the code by limsim, so I have created my own pull request with the correct formatting.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hm, it looks like there are merge conflicts. Could you please pull and resolve? Thanks!

**Comment by limsim** [comment]
Resolve on my branch. Apologies for the hassle.

**Comment by LeaVerou** [comment]
Um, I still see merge conflicts?

**Comment by limsim** [comment]
Please use https://github.com/LeaVerou/dpi/pull/107

After that this branch can be closed. I believe Jamboozlez created this branch to try to fix my formatting. Apologies for the confusion.

**Comment by LeaVerou** [comment]
Um, I’m very confused. The other PR points to this one and you’re pointing to the other one. It’s a loop! :)

**Comment by limsim** [comment]
Root cause was my mistake anyway.

**Pull request closed without merging**
