### PR TITLE
added MacBook Pro

### PR DESCRIPTION
**Pull request by ghost**
Beside Retina displays, Apple still offers Hi-Res display options. Above 900p but below Retina resolution.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks! Are you sure Hi-Res is the actual name? Never heard of it.

**Comment by ghost** [comment]
No, it was (still is) just a name for an customization option ~~(before Apple came up with the Retina name)~~.
http://store.apple.com/us_smb_78313/configure/MD103LL/A

**Comment by LeaVerou** [comment]
Then lets just use "Apple MacBook Pro". Names don’t have to be unique, there are multiple "Apple MacBook Air" for instance.

**Comment by ghost** [comment]
I am fine with it :)

**Comment by ghost** [comment]
I press the wrong buttons today too often >__<

**Comment by LeaVerou** [comment]
Um, it still says "Apple MacBook Pro Hi-Res"...

**Comment by og2t** [comment]
+1 here

I've got one at work, 15 inch one, the resolution is 1680x1050px @ 149 ppi.

**Comment by LeaVerou** [comment]
Hey, sorry for the delay, I wasn't notified that you added a commit. Merged now.

**Comment by ghost** [comment]
The new notification system isn't that great.

**Comment by LeaVerou** [comment]
It's better than it used to be. Before it notified you about even fewer events.

**Comment by ghost** [comment]
Okay :)
Its the wrong place here to discuss this. On your next talk close to Germany we can continue from here ;-)

**Pull request merged**
