### PR TITLE
Add 4K and Ultra HD resolution

### PR DESCRIPTION
**Pull request by henriquealho**
Let me know what you think.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks! Are there any data on how common these are? Don't recall seeing them before.

**Comment by henriquealho** [comment]
The new generation of screens will be 4K... YouTube already supports 4K and there are lots of people stating to buy 4K resolution displays.. I though about adding 8K resolution but I think that one still have a time to be common.

**Comment by LeaVerou** [comment]
So if I'm reading this right, you're saying it's not common, but it will be in the future?
Cool, we can merge this PR in the future then. :)

**Comment by stefano-xy** [comment]
I would not add 4096x2180, this is very uncommon, I'd add QHD instead (2560x1440), quite common on new monitors, and as proposed UHD (4K) that is 3840x2160.

As preset I'd also add 24" between 21" and 27".

**Pull request closed without merging**
