### PR TITLE
Easier/faster develope devices list

### PR DESCRIPTION
**Pull request by alimd**
Remove ppi from screens.json and automatic calc by js
For Easier/faster develope devices list

### CODE REVIEW

**Comment by alimd** [comment]
@LeaVerou please merge this before other add-device pull request for prevent conflict.

**Comment by LeaVerou** [comment]
That would make it slower to process, for no reason. It’s much faster for someone to calculate it once and store it than for the app to calculate it every single time, for potentially thousands of devices.

Thanks for contributing though :)

**Comment by alimd** [comment]
:-1: its for some milliseconds !

**Comment by LeaVerou** [comment]
Now. What if there are many more devices in the future?

**Comment by alimd** [comment]
Then loading more bit is take longer than calculating !

**Comment by alimd** [comment]
anyway its your project, sorry

**Comment by alimd** [comment]
@LeaVerou I'm so sorry but could you please check these links ?
1. Download sample json with 1344 records and ppi http://jsbin.com/imewed/6/edit?javascript,live
2. Calculation sample json with 1344 records without ppi http://jsbin.com/imewed/5/edit?javascript,live
If you changed your mind please tell me to send new pull request
Thank you.

**Comment by LeaVerou** [comment]
Hi there,

It’s not just the speed issue. Sometimes the PPI reported by the company is different than the computed one. For example, the metrics Apple provides for iPhone 4(S) calculate to 330PPI, but Apple says it’s 326...

In fact, after giving it some thought, I decided the speed issue is insignificant, since it's just some basic math. But the above issue is...

**Comment by alimd** [comment]
Ok
We can change code to this

``` javascript
Devices.forEach(function (device) {
  device.ppi || (device.ppi = calcDpi(device.w,device.h,device.d) );
  deviceRow(device, fragment);
});
```

**Comment by LeaVerou** [comment]
Ah, that’s a good idea. Only specify it in those cases. Then in the future we could even style those somehow to indicate the provided metrics don’t add up.

So, feel free to send the PR. Please don't use `Math.pow` for squaring, it’s faster to just do `w*w`, not to mention shorter. I prefer to use `Math.pow` for powers > 3.

Also, in the above code you have a redundant `device.ppi =`. This would do:

``` javascript
Devices.forEach(function (device) {
  device.ppi = device.ppi || calcDpi(device.w,device.h,device.d);
  deviceRow(device, fragment);
});
```

or, for slightly better performance (a.k.a. premature optimization :P):

``` javascript
Devices.forEach(function (device) {
  if (!('ppi' in device)) {
    device.ppi = calcDpi(device.w,device.h,device.d);
  }
  deviceRow(device, fragment);
});
```

**Comment by alimd** [comment]
Ok thank you very much

**Comment by alimd** [comment]
> for slightly better performance (a.k.a. premature optimization :P):

I'm so so sorry @LeaVerou but check this http://jsperf.com/dpi-calc :D
your way 64% slower !

**Comment by LeaVerou** [comment]
My point was to avoid re-assigning a value if it already exists. Neither of those examples does that, so they should all be fine. It wasn't to use an `if` or an `in` operator.

**Pull request closed without merging**
