### PR TITLE
Add Google Nexus 5 to screens.json

### PR DESCRIPTION
**Pull request by dconnolly**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks, could you resolve the merge conflicts please?
Also, you accidentally added your editor config!

**Comment by arkon** [comment]
This device is already in `screens.json`.

**Comment by LeaVerou** [comment]
Thanks @arkon! Since you seem interested in helping out, I just gave you commit access!

**Comment by arkon** [comment]
@LeaVerou Thanks! I'll clean up some stuff.

**Pull request closed without merging**
