### PR TITLE
added Samsung Galaxy Young and Sony Xperia Miro

### PR DESCRIPTION
**Pull request by limsim**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi there! Thanks for contributing! Could you please follow the code style of the rest of the project and use tabs? Thanks!

**Comment by incognitojam** [comment]
Please see #110 - I have created a new pull request with the correct code style.

**Comment by limsim** [comment]
Fixed the merge conflict. Thank Jamboozlez for fixing my formatting. At work we use 2 space tabs rather than 4 spaces so that's what my IDE is set to.

**Comment by LeaVerou** [comment]
Could you please pull in recent changes, as there are still merge conflicts?
Also, please make sure these devices have not been added in the meantime.
Thanks & sorry for the delay!

**Comment by LeaVerou** [comment]
Closed via #180

**Pull request closed without merging**
