### PR TITLE
Adding Surface Pro 4

### PR DESCRIPTION
**Pull request by Alanaktion**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks but merge conflicts :(

**Comment by Alanaktion** [comment]
I've resolved the conflicts.

**Comment by LeaVerou** [comment]
It still has conflicts though :(

**Comment by Alanaktion** [comment]
I've resolved them again. The conflicts happen when multiple people change the same part of the same file, so when you merge some pull requests, it can cause conflicts in others.

**Comment by LeaVerou** [comment]
Thanks! Btw, we don't include ppi when it's automatically calculated, only when the value the manufacturer provides is different than what is automatically calculated. Can you please remove the ppi value?

**Comment by Alanaktion** [comment]
Okay, I've removed the ppi.

**Comment by LeaVerou** [comment]
Thanks, merged!

**Pull request merged**
